/* Generated by scripts/generate-glyph-atlas.py. */
#ifndef AURORAAZ_GLYPH_ATLAS_H
#define AURORAAZ_GLYPH_ATLAS_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define AZ_GLYPH_ATLAS_WIDTH 1024u
#define AZ_GLYPH_ATLAS_HEIGHT 128u
#define AZ_GLYPH_ATLAS_PIXEL_COUNT 131072u
#define AZ_MODE_NOTICE_WIDTH 192u
#define AZ_MODE_NOTICE_HEIGHT 40u
#define AZ_MODE_NOTICE_Y 72u
#define AZ_MODE_NOTICE_FILTER_X 256u
#define AZ_GLYPH_ATLAS_GLYPH_COUNT 28u
#define AZ_GLYPH_ATLAS_ROW_ADVANCE 998u
#define AZ_GLYPH_ATLAS_TEXT_TOP 20u
#define AZ_GLYPH_ATLAS_BASELINE 48u
#define AZ_GLYPH_ATLAS_TEXT_BOTTOM 53u
#define AZ_GLYPH_ATLAS_SOLID_X 1017u
#define AZ_GLYPH_ATLAS_SOLID_Y 57u

typedef struct AzGlyphAtlasGlyph {
    uint16_t source_x;
    uint16_t advance;
} AzGlyphAtlasGlyph;

extern const AzGlyphAtlasGlyph
    g_az_glyph_atlas_glyphs[AZ_GLYPH_ATLAS_GLYPH_COUNT];

size_t az_glyph_atlas_rle_size(void);
uint8_t az_glyph_atlas_decode(uint8_t *destination, size_t capacity);
const char *az_glyph_atlas_source_font_sha256(void);

#ifdef __cplusplus
}
#endif

#endif
