/* Generated by scripts/generate-glyph-atlas.py. */
#ifndef AURORAAZ_GLYPH_ATLAS_H
#define AURORAAZ_GLYPH_ATLAS_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define AZ_GLYPH_ATLAS_WIDTH 1024u
#define AZ_GLYPH_ATLAS_HEIGHT 64u
#define AZ_GLYPH_ATLAS_PIXEL_COUNT 65536u
#define AZ_GLYPH_ATLAS_GLYPH_COUNT 27u
#define AZ_GLYPH_ATLAS_ROW_ADVANCE 922u
#define AZ_GLYPH_ATLAS_TEXT_TOP 20u
#define AZ_GLYPH_ATLAS_BASELINE 48u
#define AZ_GLYPH_ATLAS_TEXT_BOTTOM 53u

typedef struct AzGlyphAtlasGlyph {
    uint16_t source_x;
    uint16_t advance;
} AzGlyphAtlasGlyph;

extern const AzGlyphAtlasGlyph
    g_az_glyph_atlas_glyphs[AZ_GLYPH_ATLAS_GLYPH_COUNT];

size_t az_glyph_atlas_rle_size(void);
uint8_t az_glyph_atlas_decode(uint8_t *destination, size_t capacity);
const char *az_glyph_atlas_source_font_sha256(void);

#ifdef __cplusplus
}
#endif

#endif
