#!/usr/bin/env python3
"""Generate Aurora A-Z's deterministic embedded Roboto Light glyph atlas."""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path

import PIL
from PIL import Image, ImageDraw, ImageFont


LABELS = ("ALL", "#", *tuple("ABCDEFGHIJKLMNOPQRSTUVWXYZ"))
ROW_TEXT = " ".join(LABELS)
ATLAS_WIDTH = 1024
ATLAS_HEIGHT = 64
FONT_SIZE = 39
BASELINE = 48
EXPECTED_FONT_SHA256 = (
    "59123d9f5a81091626fb1b37c583510a85db1296ab794b48309aaad0410232ed"
)
EXPECTED_ROW_ADVANCE = 998
EXPECTED_PILLOW_VERSION = "12.2.0"
SOLID_X = 1016
SOLID_Y = 56
SOLID_SIZE = 4


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--font", required=True, type=Path)
    parser.add_argument("--header", required=True, type=Path)
    parser.add_argument("--source", required=True, type=Path)
    parser.add_argument("--preview", type=Path)
    return parser.parse_args()


def rle_encode(pixels: bytes) -> bytes:
    encoded = bytearray()
    value = pixels[0]
    count = 0

    for pixel in pixels:
        if pixel == value and count < 255:
            count += 1
        else:
            encoded.extend((count, value))
            value = pixel
            count = 1

    encoded.extend((count, value))
    return bytes(encoded)


def byte_rows(data: bytes, width: int = 16) -> str:
    lines = []
    for offset in range(0, len(data), width):
        row = ", ".join(f"0x{value:02X}u" for value in data[offset:offset + width])
        lines.append(f"    {row},")
    return "\n".join(lines)


def write_header(path: Path) -> None:
    content = """/* Generated by scripts/generate-glyph-atlas.py. */
#ifndef AURORAAZ_GLYPH_ATLAS_H
#define AURORAAZ_GLYPH_ATLAS_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define AZ_GLYPH_ATLAS_WIDTH 1024u
#define AZ_GLYPH_ATLAS_HEIGHT 64u
#define AZ_GLYPH_ATLAS_PIXEL_COUNT 65536u
#define AZ_GLYPH_ATLAS_GLYPH_COUNT 28u
#define AZ_GLYPH_ATLAS_ROW_ADVANCE 998u
#define AZ_GLYPH_ATLAS_TEXT_TOP 20u
#define AZ_GLYPH_ATLAS_BASELINE 48u
#define AZ_GLYPH_ATLAS_TEXT_BOTTOM 53u
#define AZ_GLYPH_ATLAS_SOLID_X 1017u
#define AZ_GLYPH_ATLAS_SOLID_Y 57u

typedef struct AzGlyphAtlasGlyph {
    uint16_t source_x;
    uint16_t advance;
} AzGlyphAtlasGlyph;

extern const AzGlyphAtlasGlyph
    g_az_glyph_atlas_glyphs[AZ_GLYPH_ATLAS_GLYPH_COUNT];

size_t az_glyph_atlas_rle_size(void);
uint8_t az_glyph_atlas_decode(uint8_t *destination, size_t capacity);
const char *az_glyph_atlas_source_font_sha256(void);

#ifdef __cplusplus
}
#endif

#endif
"""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")


def write_source(
    path: Path,
    encoded: bytes,
    glyph_metrics: list[tuple[int, int]],
) -> None:
    metrics = "\n".join(
        f"    {{ {source_x}u, {advance}u }},"
        for source_x, advance in glyph_metrics
    )
    content = f"""/* Generated by scripts/generate-glyph-atlas.py.
 * Typeface: Roboto Light 3.016, Copyright 2011 The Roboto Project Authors.
 * License: SIL Open Font License 1.1; see third_party/roboto/OFL.txt.
 */
#include <stddef.h>
#include <stdint.h>

#include <auroraaz/glyph_atlas.h>

static const uint8_t k_glyph_atlas_rle[] = {{
{byte_rows(encoded)}
}};

const AzGlyphAtlasGlyph
    g_az_glyph_atlas_glyphs[AZ_GLYPH_ATLAS_GLYPH_COUNT] = {{
{metrics}
}};

size_t az_glyph_atlas_rle_size(void)
{{
    return sizeof(k_glyph_atlas_rle);
}}

uint8_t az_glyph_atlas_decode(uint8_t *destination, size_t capacity)
{{
    size_t input_offset;
    size_t output_offset = 0u;

    if (destination == NULL || capacity < AZ_GLYPH_ATLAS_PIXEL_COUNT) {{
        return 0u;
    }}

    for (input_offset = 0u;
         input_offset < sizeof(k_glyph_atlas_rle);
         input_offset += 2u) {{
        const size_t count = (size_t)k_glyph_atlas_rle[input_offset];
        const uint8_t value = k_glyph_atlas_rle[input_offset + 1u];
        size_t run_offset;

        if (count == 0u ||
            output_offset > AZ_GLYPH_ATLAS_PIXEL_COUNT - count) {{
            return 0u;
        }}

        for (run_offset = 0u; run_offset < count; ++run_offset) {{
            destination[output_offset + run_offset] = value;
        }}
        output_offset += count;
    }}

    return output_offset == AZ_GLYPH_ATLAS_PIXEL_COUNT ? 1u : 0u;
}}

const char *az_glyph_atlas_source_font_sha256(void)
{{
    return "{EXPECTED_FONT_SHA256.upper()}";
}}
"""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")


def main() -> None:
    args = parse_args()
    if PIL.__version__ != EXPECTED_PILLOW_VERSION:
        raise SystemExit(
            "Pillow version mismatch: "
            f"expected {EXPECTED_PILLOW_VERSION}, got {PIL.__version__}"
        )

    font_bytes = args.font.read_bytes()
    font_hash = hashlib.sha256(font_bytes).hexdigest()
    if font_hash != EXPECTED_FONT_SHA256:
        raise SystemExit(
            f"Roboto Light source hash mismatch: {font_hash}"
        )

    font = ImageFont.truetype(str(args.font), FONT_SIZE)
    row_advance = round(font.getlength(ROW_TEXT))
    if row_advance != EXPECTED_ROW_ADVANCE:
        raise SystemExit(
            f"Unexpected glyph metrics: row advance is {row_advance}"
        )

    image = Image.new("L", (ATLAS_WIDTH, ATLAS_HEIGHT), 0)
    draw = ImageDraw.Draw(image)
    draw.text((0, BASELINE), ROW_TEXT, font=font, fill=255, anchor="ls")
    draw.rectangle(
        (SOLID_X, SOLID_Y, SOLID_X + SOLID_SIZE - 1, SOLID_Y + SOLID_SIZE - 1),
        fill=255,
    )

    glyph_metrics: list[tuple[int, int]] = []
    cursor = 0.0
    separator_advance = font.getlength(" ")
    for index, label in enumerate(LABELS):
        advance = font.getlength(label)
        glyph_metrics.append((round(cursor), round(advance)))
        cursor += advance
        if index + 1 < len(LABELS):
            cursor += separator_advance

    pixels = image.tobytes()
    encoded = rle_encode(pixels)
    write_header(args.header)
    write_source(args.source, encoded, glyph_metrics)

    if args.preview is not None:
        args.preview.parent.mkdir(parents=True, exist_ok=True)
        image.save(args.preview)

    print(
        f"generated {len(pixels)} pixels as {len(encoded)} RLE bytes; "
        f"row advance {row_advance}"
    )


if __name__ == "__main__":
    main()
